#! /bin/sh

td_agent_dir=/usr/lib/fluent
if [ -d "/usr/lib64/fluent" ]; then
        td_agent_dir=/usr/lib64/fluent
fi

if [ $1 = 0 ] ; then
  rm /etc/init.d/td-agent
  rm /usr/bin/td
  rm /usr/sbin/td-agent
  rm -rf /etc/td-agent/logrotate.d/td-agent.logrotate
  rm -rf /etc/td-agent/prelink.conf.d/td-agent.conf
  rm -rf ${td_agent_dir}
  rm -rf /var/log/td-agent
  rm -rf /var/lib/td-agent
fi
