dir 'plugin_gems'
download "td-client", "0.8.56"
download "td", "0.10.96"
download "fluent-plugin-td", "0.10.17"
download "thrift", "0.8.0"
download "fluent-plugin-scribe", "0.10.10"
download "fluent-plugin-flume", "0.1.1"
download "bson", "1.8.6"
download "bson_ext", "1.8.6"
download "mongo", "1.8.6"
download "fluent-plugin-mongo", "0.7.1"
download "aws-sdk", "1.8.3.1"
download "fluent-plugin-s3", "0.3.5"
download "webhdfs", "0.5.3"
download "fluent-plugin-webhdfs", "0.2.1"
download "fluent-plugin-rewrite-tag-filter", "1.3.1"
download "fluent-plugin-td-monitoring", "0.1.0"
