#!/bin/bash
#
# /etc/rc.d/init.d/<%= project_name %>
#
# chkconfig: - 80 20
# description: <%= project_name %>
# processname: <%= project_name %>
# pidfile: /var/run/<%= project_name %>/<%= project_name %>.pid
#
### BEGIN INIT INFO
# Provides:          <%= project_name %>
# Default-Stop:      0 1 6
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Short-Description: <%= project_name %>'s init script
# Description:       <%= project_name %> is a data collector
### END INIT INFO

set -e

# Source function library.
. /etc/init.d/functions

name="<%= project_name %>"
prog="<%= project_name %>"
process_bin=<%= install_path %>/embedded/bin/ruby

# timeout can be overridden from /etc/sysconfig/<%= project_name %>
STOPTIMEOUT=120

if [ -f /etc/sysconfig/$prog ]; then
	. /etc/sysconfig/$prog
fi
PIDFILE=${PIDFILE-/var/run/<%= project_name %>/$prog.pid}
DAEMON_ARGS=${DAEMON_ARGS---user <%= project_name %>}
<%= project_name_snake_upcase %>_ARGS="${<%= project_name_snake_upcase %>_ARGS-/usr/sbin/<%= project_name %> --group <%= project_name %> --log /var/log/<%= project_name %>/<%= project_name %>.log --use-v1-config}"

if [ -n "${PIDFILE}" ]; then
	PIDFILE_DIR=$(dirname ${PIDFILE})
	if [ ! -e $PIDFILE_DIR ]; then
		mkdir -p $PIDFILE_DIR
	fi
	chown -R <%= project_name %>:<%= project_name %> $PIDFILE_DIR
	<%= project_name_snake_upcase %>_ARGS="${<%= project_name_snake_upcase %>_ARGS} --daemon ${PIDFILE}"
fi

# 2012/04/17 Kazuki Ohta <k@treasure-data.com>
# use jemalloc to avoid fragmentation
if [ -f "<%= install_path %>/embedded/lib/libjemalloc.so" ]; then
        export LD_PRELOAD=<%= install_path %>/embedded/lib/libjemalloc.so
fi

RETVAL=0

start() {
	# Set Max number of file descriptors for the safety sake
	# see http://docs.fluentd.org/en/articles/before-install
	ulimit -n 65536
	echo -n "Starting $name: "
	daemon --pidfile=$PIDFILE $DAEMON_ARGS $process_bin "$<%= project_name_snake_upcase %>_ARGS"
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch /var/lock/subsys/$prog
	return $RETVAL
}

stop() {
	echo -n "Shutting down $name: "
	if [ -e "${PIDFILE}" ]; then
	    # Use own process termination instead of killproc because killproc can't wait SIGTERM
	    <%= project_name_snake_upcase %>_PID=`cat "$PIDFILE" 2>/dev/null`
	    if [ -n "$<%= project_name_snake_upcase %>_PID" ]; then
		/bin/kill "$<%= project_name_snake_upcase %>_PID" >/dev/null 2>&1
		RETVAL=$?
		if [ $RETVAL -eq 0 ]; then
		    TIMEOUT="$STOPTIMEOUT"
		    while [ $TIMEOUT -gt 0 ]; do
			/bin/kill -0 "$<%= project_name_snake_upcase %>_PID" >/dev/null 2>&1 || break
			sleep 1
			let TIMEOUT=${TIMEOUT}-1
		    done
		    if [ $TIMEOUT -eq 0 ]; then
			echo -n "Timeout error occurred trying to stop <%= project_name %>..."
			RETVAL=1
			failure
		    else
			RETVAL=0
			success
		    fi
		else
		    failure
		fi
	    else
		failure
		RETVAL=4
	    fi
	else
	    killproc $prog
	    RETVAL=$?
	    if [ $RETVAL -eq 0 ]; then
		success
	    else
		failure
	    fi
	fi
	echo
	[ $RETVAL -eq 0 ] && rm -f $PIDFILE && rm -f /var/lock/subsys/$prog
	return $RETVAL
}

restart() {
	configtest || return $?
	stop
	start
}

reload() {
	configtest || return $?
	echo -n "Reloading $name: "
	killproc $process_bin -HUP
	RETVAL=$?
	echo
}

configtest() {
	eval "$<%= project_name_snake_upcase %>_ARGS $DAEMON_ARGS --dry-run -q"
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart)
	restart
	;;
    reload)
	reload
	;;
    condrestart)
	[ -f /var/lock/subsys/$prog ] && restart || :
	;;
    configtest)
        configtest
        ;;
    status)
	status -p $PIDFILE '<%= project_name %>'
	;;
    *)
	echo "Usage: $prog {start|stop|reload|restart|condrestart|status|configtest}"
	exit 1
	;;
esac
exit $?
