#!/bin/bash
#
# Install a full <%= project_name %>
#

<%= project_name_snake %>_dir=/opt/<%= project_name %>

# Create <%= project_name %> related directories and files

if [ ! -e "/var/log/<%= project_name %>/" ]; then
  mkdir -p /var/log/<%= project_name %>/
  mkdir -p /var/log/<%= project_name %>/buffer/
fi
if [ ! -e "/var/run/<%= project_name %>/" ]; then
  mkdir -p /var/run/<%= project_name %>/
fi
if [ ! -e "/etc/<%= project_name %>/" ]; then
  mkdir -p /etc/<%= project_name %>/
  mkdir -p /etc/<%= project_name %>/plugin
fi
if [ ! -e "/etc/<%= project_name %>/<%= project_name %>.conf" ]; then
  echo "Installing default conffile..."
  cp -f $<%= project_name_snake %>_dir/etc/<%= project_name %>/<%= project_name %>.conf.tmpl /etc/<%= project_name %>/<%= project_name %>.conf
fi
if [ ! -e "/tmp/<%= project_name %>/" ]; then
  mkdir -p /tmp/<%= project_name %>/
fi

cp -f $<%= project_name_snake %>_dir/usr/sbin/<%= project_name %> /usr/sbin/<%= project_name %>
chmod 755 /usr/sbin/<%= project_name %>
cp -f $<%= project_name_snake %>_dir/usr/sbin/<%= project_name %>-gem /usr/sbin/<%= project_name %>-gem
chmod 755 /usr/sbin/<%= project_name %>-gem
if [ -f "$<%= project_name_snake %>_dir/usr/sbin/<%= project_name %>-ui" ]; then
    cp -f $<%= project_name_snake %>_dir/usr/sbin/<%= project_name %>-ui /usr/sbin/<%= project_name %>-ui
    chmod 755 /usr/sbin/<%= project_name %>-ui
fi
if [ -f "$<%= project_name_snake %>_dir/usr/bin/td" ]; then
    cp -f $<%= project_name_snake %>_dir/usr/bin/td /usr/bin/td
    chmod 755 /usr/bin/td
fi
cp -f $<%= project_name_snake %>_dir/<%= project_name %>.plist /Library/LaunchDaemons/

exit 0
