#! /bin/sh

set -e

if [ "$1" = "purge" ]; then
        rm -f /etc/default/<%= project_name %>
        rm -f /etc/<%= project_name %>/<%= project_name %>.conf
	dpkg-statoverride --list /etc/<%= project_name %> > /dev/null && \
		dpkg-statoverride --remove /etc/<%= project_name %>
	rm -f /var/run/<%= project_name %>/*
	dpkg-statoverride --list /var/run/<%= project_name %> > /dev/null && \
		dpkg-statoverride --remove /var/run/<%= project_name %>
	rm -rf /var/log/<%= project_name %>/buffer
	rm -rf /var/log/<%= project_name %>/*
	dpkg-statoverride --list /var/log/<%= project_name %> > /dev/null && \
		dpkg-statoverride --remove /var/log/<%= project_name %>

    rm /etc/init.d/<%= project_name %>
    rm /usr/sbin/<%= project_name %>
    rm /usr/sbin/<%= project_name %>-gem

    getent passwd <%= project_name %> && userdel -r <%= project_name %>

    if [ -f /usr/sbin/<%= project_name %>-ui ]; then
        rm /usr/sbin/<%= project_name %>-ui
    fi
    if [ -f /usr/bin/td ]; then
        rm /usr/bin/td
    fi
    if [ -f /etc/logrotate.d/<%= project_name %> ]; then
        rm /etc/logrotate.d/<%= project_name %>
    fi

fi

# Automatically added by dh_makeshlibs
if [ "$1" = "remove" ]; then
	ldconfig
fi
# End automatically added section
# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d <%= project_name %> remove >/dev/null
fi
# End automatically added section
