#! /bin/sh

set -e

<%= project_name_snake %>_dir=<%= install_path %>

prevver="$2"

add_system_user() {
    if ! getent passwd <%= project_name %> >/dev/null; then
        adduser --group --system --no-create-home <%= project_name %>
    fi
}

add_directories() {
    mkdir -p /var/run/<%= project_name %>
    mkdir -p /etc/<%= project_name %>
    mkdir -p /etc/<%= project_name %>/plugin
    mkdir -p /etc/<%= project_name %>/baseline
    mkdir -p /var/log/<%= project_name %>
}

fixperms() {
    dpkg-statoverride --list /var/run/<%= project_name %> >/dev/null || \
        dpkg-statoverride --update --add <%= project_name %> <%= project_name %> 0755 /var/run/<%= project_name %>
    dpkg-statoverride --list /etc/<%= project_name %> >/dev/null || \
        dpkg-statoverride --update --add <%= project_name %> <%= project_name %> 0755 /etc/<%= project_name %>
    dpkg-statoverride --list /var/log/<%= project_name %> >/dev/null || \
        dpkg-statoverride --update --add <%= project_name %> <%= project_name %> 0755 /var/log/<%= project_name %>
}

update_conffile() {
    CONFFILE="$1"
    TMPL="$2"

    if [ -e "$CONFFILE" ]; then
        md5sum="`md5sum \"$CONFFILE\" | sed -e \"s/ .*//\"`"
        old_md5sum="`sed -n -e \"/^Conffiles:/,/^[^ ]/{\\\\' $TMPL'{s/.* //;p}}\" /var/lib/dpkg/status`"
        if [ -z "$old_md5sum" ]; then
           # backward compatibility
            old_md5sum="`sed -n -e \"/^Conffiles:/,/^[^ ]/{\\\\' $CONFFILE'{s/.* //;p}}\" /var/lib/dpkg/status`"
        fi

        if [ "$md5sum" != "$old_md5sum" ]; then
            echo "Conffile $CONFFILE has been modified. Remain untouched."
            # do nothing
        else
            echo "Updating conffile $CONFFILE ..."
            cp -f "$TMPL" "$CONFFILE"
        fi
    else
        echo "Installing default conffile $CONFFILE ..."
        cp -f "$TMPL" "$CONFFILE"
    fi

    # 2011/11/13 Kazuki Ohta <k@treasure-data.com>
    # Before td-agent v1.1.0, fluentd has a bug of loading plugin before
    # changing to the right user. Then, these directories were created with
    # root permission. The following lines fix that problem.
    if [ -d "/var/log/<%= project_name %>/buffer/" ]; then
        chown -R <%= project_name %>:<%= project_name %> /var/log/<%= project_name %>/buffer/
    fi
    if [ -d "/tmp/<%= project_name %>/" ]; then
        chown -R <%= project_name %>:<%= project_name %> /tmp/<%= project_name %>/
    fi
}

case "$1" in
    configure)
        add_system_user
        add_directories
        fixperms
        update_conffile /etc/<%= project_name %>/<%= project_name %>.conf ${<%= project_name_snake %>_dir}/etc/<%= project_name %>/<%= project_name %>.conf.tmpl
        update_conffile /etc/<%= project_name %>/baseline/<%= project_name %>.conf ${<%= project_name_snake %>_dir}/etc/<%= project_name %>/<%= project_name %>.conf.tmpl
        sed -i 's/@include config\.d\/\*\.conf/@include config.d\/baseline\/*.conf/g' /etc/<%= project_name %>/baseline/<%= project_name %>.conf
        ;;
    abort-upgrade|abort-deconfigure|abort-remove)
        :
        ;;
    *)
        echo "Called with unknown argument $1, bailing out."
        exit 1
        ;;
esac


cp -f ${<%= project_name_snake %>_dir}/etc/init.d/<%= project_name %> /etc/init.d/<%= project_name %>
cp -f ${<%= project_name_snake %>_dir}/usr/sbin/<%= project_name %> /usr/sbin/<%= project_name %>
chmod 755 /usr/sbin/<%= project_name %>
cp -f ${<%= project_name_snake %>_dir}/usr/sbin/<%= project_name %>-gem /usr/sbin/<%= project_name %>-gem
chmod 755 /usr/sbin/<%= project_name %>-gem
if [ -f ${<%= project_name_snake %>_dir}/usr/sbin/<%= project_name %>-ui ]; then
    cp -f ${<%= project_name_snake %>_dir}/usr/sbin/<%= project_name %>-ui /usr/sbin/<%= project_name %>-ui
    chmod 755 /usr/sbin/<%= project_name %>-ui
fi
if [ -f ${<%= project_name_snake %>_dir}/usr/bin/td ]; then
    cp -f ${<%= project_name_snake %>_dir}/usr/bin/td /usr/bin/td
    chmod 755 /usr/bin/td
fi

if [ -d "/etc/logrotate.d/" ]; then
  cp -f ${<%= project_name_snake %>_dir}/etc/<%= project_name %>/logrotate.d/<%= project_name %>.logrotate /etc/logrotate.d/<%= project_name %>
fi

if [ ! -e "/etc/default/<%= project_name %>" ]; then
  cat > /etc/default/<%= project_name %> <<EOF
# This file is sourced by /bin/sh from /etc/init.d/<%= project_name %>
# Options to pass to <%= project_name %>
TD_AGENT_OPTIONS=""

EOF
fi

# Automatically added by dh_installinit
if [ -x "/etc/init.d/<%= project_name %>" ]; then
	if [ ! -e "/etc/init/<%= project_name %>.conf" ]; then
		update-rc.d <%= project_name %> defaults >/dev/null
	fi
	invoke-rc.d <%= project_name %> start || exit $?
fi
# End automatically added section
# Automatically added by dh_makeshlibs
if [ "$1" = "configure" ]; then
	ldconfig
fi
# End automatically added section
